### ISSUE TITLE
min-duration(?) option

### ISSUE THREAD

**Issue by syuilo** [tj/node-ratelimiter#18]
Thank you for the awesome module.

I want the ability to block and not after a few seconds from the last access.
(In order to prevent the continuous access of a very short period of time)

Sorry my English

**Comment by noamshemesh** [comment]
as far as I understand your request, that's exactly what the module knows to do.
try setting the `duration` option to short period of time and `max` option to a relatively low value.
don't forget that with express (or any other middleware) you can set more than one `ratelimiter`.

**Comment by syuilo** [comment]
Oh, now I get it.
Thank you!
