### ISSUE TITLE
Reatelimiter not able to create redis key

### ISSUE THREAD

**Issue by AlexJangam** [tj/node-ratelimiter#23]
function create() {
    var ex = (Date.now() + duration) / 1000 | 0;
   //written for testing code
    db.set([count, max, 'PX', duration, 'NX'],function(er,re){
     console.log("single set",er,re);
    //error message "(error) ERR wrong number of arguments for 'set' command"
    })

    db.multi()
      .set([count, max, 'PX', duration, 'NX'])
      .set([limit, max, 'PX', duration, 'NX'])
      .set([reset, ex, 'PX', duration, 'NX'])
      .exec(function (err, res) {
        if (err) return fn(err);
        // If the request has failed, it means the values already
        // exist in which case we need to get the latest values.
        if (isFirstReplyNull(res)) return mget();//Going to infinite loop here

        fn(null, {
          total: max,
          remaining: max,
          reset: ex
        });
      });
  }

**Comment by noamshemesh** [comment]
What is your redis version?

**Comment by AlexJangam** [comment]
My previous version was 2.4. The ratelimiter is working as expected in my new version of redis 3.0.5

**Comment by noamshemesh** [comment]
Cool
