### ISSUE TITLE
TTL instead of multiple keys.

### ISSUE THREAD

**Issue by vivekannan** [tj/node-ratelimiter#24]
Not sure if the understand the module completely, so apologies if I am wrong. I was wondering if maybe the module could set a single key and use TTL to find out 'X-RateLimit-Reset'.

**Comment by noamshemesh** [comment]
Do you want to change the redis use?

**Comment by vivekannan** [comment]
No, I meant use Time To Live command to figure out the wait for duration.
http://redis.io/commands/ttl

**Comment by noamshemesh** [comment]
Yeah that's what I meant.
The main reason you want this is to get rid of the reset value, right?
There is no particular reason that I can think about why not changing it, besides maybe people rely on this values when they use this module.

**Comment by noamshemesh** [comment]
BTW we should use PTTL as we want the millis to expire

**Comment by vivekannan** [comment]
I think the module should internally make use of the PTTL command to get
the reset time, instead of making use of multiple keys. I am not saying
that the reset value itself should be removed from the module, just think
that the way it is computed should be changed.

**Comment by noamshemesh** [comment]
Is there any reason you want this?

**Comment by vivekannan** [comment]
Don't have any particular reason. Using PTTL would probably be more
accurate. Also, number of keys set would reduce. Given that this repo will
probably used in scenarios where there are 100's of concurrent requests, I
think the above two points would be of great advantage. Just my two cents,
the final decision is yours, obviously.

**Comment by noamshemesh** [comment]
Sounds reasonable, though I won't be able to write it in the next few months. I'd love to get a working PR from you or anyone else

**Comment by noamshemesh** [comment]
Closing for now

**Comment by vivekannan** [comment]
Ok. I have re-written index.js so that it makes use of only one key. I have two doubts before making a pull request.

1. If all the mocha tests pass successfully, can I safely assume that there is no race condition issues? I checked the concurrent test with 1000 clients and it still succeeded.
2. Can I use multi().decr() instead of multi().set(key, count -1)? Any reason for not using decr()?

Thanks.

**Comment by noamshemesh** [comment]
Sorry for the late response.
Feel free to create the PR, I will review it.
Regarding what you wrote:

1. Yes, it should be enough
1. To prevent minuses counts, try to imagine 2 calls in parallel that passed the test and both are going to decrease the value, it will result count of -1. Currently the count will be zero and both calls will be accepted

**Comment by vivekannan** [comment]
Ok. The pull request still uses mutli().decr(). You can make changes as you please.
