### ISSUE TITLE
Reset functionality

### ISSUE THREAD

**Issue by Bramzor** [tj/node-ratelimiter#26]
We are trying to use node-ratelimiter for BFD protection purposes of logins.
This is easy to do, the only issue is that there is no way to reset after a successful login.

Good idea to add this to the code? Any idea on where to start?

**Comment by noamshemesh** [comment]
Yeah I understand, it might be tricky. Unfortunately I don't have time to deal with that right now :(
If someone can create a PR, I'll merge it.

In the meanwhile, you can delete the key from redis after a successful login
