### ISSUE TITLE
Compatibility issue with ioredis-mock

### ISSUE THREAD

**Issue by edwmurph** [tj/node-ratelimiter#28]
Currently ioredis-mock only supports `multi()` when the transactional commands are passed as an array of arguments. How easily could you switch to the supported array syntax?

ex.
Change all multi's from

`
db.multi().set('foo', 'bar').get('foo')...
`
to
`
db.multi([
  ['set', 'foo', 'bar'],
  ['get', 'foo']
])...
`

Also, I verified that this array syntax for multi is also compatible with ioredis, node_redis, and fakeredis.

**Comment by noamshemesh** [comment]
It seems like ioredis-mock is under development, I'm pretty sure that after fixing this issue we'll encounter other incompatibilities as they didn't develop most of the features. (e.g.: https://github.com/stipsan/ioredis-mock/issues/197).

I think we shouldn't support this package right now.

**Comment by stipsan** [comment]
😉  https://github.com/stipsan/ioredis-mock/pull/294

**Comment by benjamingr** [comment]
This is broken at the moment. `TypeError: db.multi(...).zremrangebyscore is not a function`
