### ISSUE TITLE
more than one limiter

### ISSUE THREAD

**Issue by innovationnow** [tj/node-ratelimiter#35]
how can i deploy 2 limiters?

**Comment by noamshemesh** [comment]
Hi,

you can create 2 instances of Limiter

```
const id = req.user._id
const limit = new Limiter({ id, db })
const limit2 = new Limiter({ id, db })
limit.get((err, limit) => { ... })
limit2.get((err, limit) => { ... })
```

**Comment by Offirmo** [comment]
But then won't they try using the same entries in the DB?

**Comment by noamshemesh** [comment]
Hi @Offirmo, you can create a different db instances and select a different logical database (https://redis.io/commands/select)
