### ISSUE TITLE
limit.reset always 1499329365

### ISSUE THREAD

**Issue by parav01d** [tj/node-ratelimiter#36]
In your example the value of "limit.reset" 
`res.set('X-RateLimit-Reset', limit.reset);`
is always "1499329365". Everything else works fine but this value is unchanged. 
And the "duration" option will not be accepted. 
` var limit = new Limiter({
                id: apikey,
                db: sails.redis,
                max: 100,
                duration : 3600000
            });`

**Comment by noamshemesh** [comment]
The reset header value is the time since epoch in seconds that the rate limiting period will be ended (or already ended).
I'm not sure what you're asking here but if you encounter a bug please provide some code to reproduce it
