### ISSUE TITLE
Possible units confusion

### ISSUE THREAD

**Issue by bard** [tj/node-ratelimiter#39]
Is the `reset` parameter:

- supposed to be expressed in seconds or milliseconds?
- supposed to express a time interval or an absolute time?

README.md says:

```
reset - time in milliseconds until the end of current duration
```

#36 says:

```
The reset header value is the time since epoch in seconds that the 
rate limiting period will be ended (or already ended).
```

My understanding from trial and error and reading the code is that it's an absolute time and is expressed in seconds.

**Comment by noamshemesh** [comment]
Thanks for pointing that out. Fixed the readme file
