### ISSUE TITLE
Memory consumption

### ISSUE THREAD

**Issue by Offirmo** [tj/node-ratelimiter#50]
Hi, thanks for the lib.

I'm trying to size my redis instance. Do we have any idea of the memory consumption of this lib?

For example, let's say I want to prevent more than 10 access/min and I have 2000 different client IPs per day?

What would that give?

**Comment by noamshemesh** [comment]
for each id (different ip in your case) one key is created and it expires after `reset` second (or `resetMs` milliseconds)

**Comment by Offirmo** [comment]
Awesome, thanks. This may be useful in the README.
