### ISSUE TITLE
opts tidy is a bug?

### ISSUE THREAD

**Issue by ChunMengLu** [tj/node-ratelimiter#51]
https://github.com/tj/node-ratelimiter/blob/831ee5054ce3327e328ff3cb8783ba0b4d52e0e5/index.js#L62

```js
function Limiter(opts) {
  this.id = opts.id;
  this.db = opts.db;
  this.tidy = opts.tidy || false;
  // ... ...
}
```

emmm，but `tidy = this.key` !

```js
Limiter.prototype.get = function (fn) {
  var db = this.db;
  var tidy = this.key;
  var duration = this.duration;
  // ... ...
}
```

**Comment by noamshemesh** [comment]
you are right, that means that tidy was always true until now. 
I will release a version soon without the ability to set tidy (what will make it always true) and will remove this from the documentation for now. 
Thanks

**Comment by penghap** [comment]
I‘m sorry for making such a mistake. 
now, the tidy always true, I will fix it as soon as possiable.

**Comment by noamshemesh** [comment]
Thanks @penghap

No need to submit a PR, this is a minor issue that I will fix soon. Thanks
